import type { Sport } from '../types';

/** Harder / deeper campaign title questions unlocked in later chapters. */
export interface CampaignDeepQ {
  id: string;
  sport: Sport;
  prompt: string;
  trophyIcon: string;
  trophyLabel: string;
  answer: string;
  distractors: string[];
  minLevel: number;
}

const T = {
  worldCup: '/icons/trophies/world-cup.png',
  euro: '/icons/trophies/euro-trophy.png',
  ucl: '/icons/trophies/ucl.png',
  europa: '/icons/trophies/europa.png',
  faCup: '/icons/trophies/fa-cup.png',
  copa: '/icons/trophies/copa-america.png',
  afcon: '/icons/trophies/afcon.svg',
  ballon: '/icons/trophies/ballon-dor.png',
  nba: '/icons/trophies/nba-ring.png',
  nbaMvp: '/icons/trophies/nba-mvp.png',
  mlb: '/icons/trophies/mlb-world-series.png',
  mlbMvp: '/icons/trophies/mlb-mvp.png',
  cyYoung: '/icons/trophies/mlb-cy-young.png',
  nfl: '/icons/trophies/nfl-super-bowl.png',
  nhl: '/icons/trophies/nhl-hof.png',
  generic: '/icons/trophy-record.png',
} as const;

/**
 * Niche but accurate — Copa del Rey, domestic titles, older cups, deeper awards.
 * minLevel gates them into mid/late campaign chapters.
 */
export const CAMPAIGN_DEEP_TRIVIA: CampaignDeepQ[] = [
  // ── Soccer · domestic cups & leagues (ch 2+) ──
  {
    id: 'cdr-2023',
    sport: 'soccer',
    minLevel: 12,
    prompt: 'Which club won the Copa del Rey in 2022–23?',
    trophyIcon: T.generic,
    trophyLabel: 'Copa del Rey',
    answer: 'Real Madrid',
    distractors: ['Barcelona', 'Osasuna', 'Atlético Madrid'],
  },
  {
    id: 'cdr-2024',
    sport: 'soccer',
    minLevel: 14,
    prompt: 'Which club won the Copa del Rey in 2023–24?',
    trophyIcon: T.generic,
    trophyLabel: 'Copa del Rey',
    answer: 'Athletic Club',
    distractors: ['Mallorca', 'Real Madrid', 'Barcelona'],
  },
  {
    id: 'cdr-2015',
    sport: 'soccer',
    minLevel: 22,
    prompt: 'Which club won the Copa del Rey in 2014–15?',
    trophyIcon: T.generic,
    trophyLabel: 'Copa del Rey',
    answer: 'Barcelona',
    distractors: ['Athletic Club', 'Real Madrid', 'Espanyol'],
  },
  {
    id: 'efl-2024',
    sport: 'soccer',
    minLevel: 13,
    prompt: 'Which club won the EFL Cup (Carabao Cup) in 2023–24?',
    trophyIcon: T.generic,
    trophyLabel: 'EFL Cup',
    answer: 'Liverpool',
    distractors: ['Chelsea', 'Manchester United', 'Tottenham'],
  },
  {
    id: 'efl-2022',
    sport: 'soccer',
    minLevel: 18,
    prompt: 'Which club won the EFL Cup in 2021–22?',
    trophyIcon: T.generic,
    trophyLabel: 'EFL Cup',
    answer: 'Liverpool',
    distractors: ['Chelsea', 'Manchester City', 'Tottenham'],
  },
  {
    id: 'dfb-2024',
    sport: 'soccer',
    minLevel: 15,
    prompt: 'Which club won the DFB-Pokal in 2023–24?',
    trophyIcon: T.generic,
    trophyLabel: 'DFB-Pokal',
    answer: 'Bayer Leverkusen',
    distractors: ['Kaiserslautern', 'Bayern Munich', 'Dortmund'],
  },
  {
    id: 'dfb-2023',
    sport: 'soccer',
    minLevel: 20,
    prompt: 'Which club won the DFB-Pokal in 2022–23?',
    trophyIcon: T.generic,
    trophyLabel: 'DFB-Pokal',
    answer: 'RB Leipzig',
    distractors: ['Eintracht Frankfurt', 'Bayern Munich', 'Freiburg'],
  },
  {
    id: 'coppa-2024',
    sport: 'soccer',
    minLevel: 16,
    prompt: 'Which club won the Coppa Italia in 2023–24?',
    trophyIcon: T.generic,
    trophyLabel: 'Coppa Italia',
    answer: 'Juventus',
    distractors: ['Atalanta', 'Inter', 'Fiorentina'],
  },
  {
    id: 'coppa-2021',
    sport: 'soccer',
    minLevel: 24,
    prompt: 'Which club won the Coppa Italia in 2020–21?',
    trophyIcon: T.generic,
    trophyLabel: 'Coppa Italia',
    answer: 'Juventus',
    distractors: ['Atalanta', 'Inter', 'Napoli'],
  },
  {
    id: 'cdf-2024',
    sport: 'soccer',
    minLevel: 17,
    prompt: 'Which club won the Coupe de France in 2023–24?',
    trophyIcon: T.generic,
    trophyLabel: 'Coupe de France',
    answer: 'Paris Saint-Germain',
    distractors: ['Lyon', 'Nice', 'Monaco'],
  },
  {
    id: 'seriea-2024',
    sport: 'soccer',
    minLevel: 11,
    prompt: 'Which club won Serie A in 2023–24?',
    trophyIcon: T.generic,
    trophyLabel: 'Serie A',
    answer: 'Inter',
    distractors: ['Milan', 'Juventus', 'Napoli'],
  },
  {
    id: 'laliga-2024',
    sport: 'soccer',
    minLevel: 11,
    prompt: 'Which club won La Liga in 2023–24?',
    trophyIcon: T.generic,
    trophyLabel: 'La Liga',
    answer: 'Real Madrid',
    distractors: ['Barcelona', 'Girona', 'Atlético Madrid'],
  },
  {
    id: 'bundes-2024',
    sport: 'soccer',
    minLevel: 12,
    prompt: 'Which club won the Bundesliga in 2023–24?',
    trophyIcon: T.generic,
    trophyLabel: 'Bundesliga',
    answer: 'Bayer Leverkusen',
    distractors: ['Bayern Munich', 'Stuttgart', 'Dortmund'],
  },
  {
    id: 'ligue1-2024',
    sport: 'soccer',
    minLevel: 11,
    prompt: 'Which club won Ligue 1 in 2023–24?',
    trophyIcon: T.generic,
    trophyLabel: 'Ligue 1',
    answer: 'Paris Saint-Germain',
    distractors: ['Monaco', 'Brest', 'Lille'],
  },
  {
    id: 'pl-2016',
    sport: 'soccer',
    minLevel: 19,
    prompt: 'Which club won the Premier League in 2015–16?',
    trophyIcon: T.generic,
    trophyLabel: 'Premier League',
    answer: 'Leicester City',
    distractors: ['Arsenal', 'Tottenham', 'Manchester City'],
  },
  {
    id: 'uel-2023',
    sport: 'soccer',
    minLevel: 14,
    prompt: 'Which club won the UEFA Europa League in 2023?',
    trophyIcon: T.europa,
    trophyLabel: 'Europa League',
    answer: 'Sevilla',
    distractors: ['Roma', 'Juventus', 'Leverkusen'],
  },
  {
    id: 'uel-2024',
    sport: 'soccer',
    minLevel: 13,
    prompt: 'Which club won the UEFA Europa League in 2024?',
    trophyIcon: T.europa,
    trophyLabel: 'Europa League',
    answer: 'Atalanta',
    distractors: ['Bayer Leverkusen', 'Marseille', 'Liverpool'],
  },
  {
    id: 'uecl-2024',
    sport: 'soccer',
    minLevel: 21,
    prompt: 'Which club won the UEFA Europa Conference League in 2024?',
    trophyIcon: T.generic,
    trophyLabel: 'Conference League',
    answer: 'Olympiacos',
    distractors: ['Fiorentina', 'Aston Villa', 'Club Brugge'],
  },
  {
    id: 'uecl-2022',
    sport: 'soccer',
    minLevel: 25,
    prompt: 'Which club won the first UEFA Europa Conference League (2021–22)?',
    trophyIcon: T.generic,
    trophyLabel: 'Conference League',
    answer: 'Roma',
    distractors: ['Feyenoord', 'Leicester City', 'Marseille'],
  },
  {
    id: 'afcon-2024',
    sport: 'soccer',
    minLevel: 15,
    prompt: 'Which nation won AFCON 2023 (played in 2024)?',
    trophyIcon: T.afcon,
    trophyLabel: 'AFCON',
    answer: 'Ivory Coast',
    distractors: ['Nigeria', 'Senegal', 'Egypt'],
  },
  {
    id: 'copa-2015',
    sport: 'soccer',
    minLevel: 23,
    prompt: 'Which nation won the Copa América in 2015?',
    trophyIcon: T.copa,
    trophyLabel: 'Copa América',
    answer: 'Chile',
    distractors: ['Argentina', 'Peru', 'Paraguay'],
  },
  {
    id: 'ucl-1999',
    sport: 'soccer',
    minLevel: 28,
    prompt: 'Which club won the UEFA Champions League in 1999?',
    trophyIcon: T.ucl,
    trophyLabel: 'Champions League',
    answer: 'Manchester United',
    distractors: ['Bayern Munich', 'Juventus', 'Real Madrid'],
  },
  {
    id: 'ucl-2005',
    sport: 'soccer',
    minLevel: 26,
    prompt: 'Which club won the UEFA Champions League in 2005 (Istanbul final)?',
    trophyIcon: T.ucl,
    trophyLabel: 'Champions League',
    answer: 'Liverpool',
    distractors: ['Milan', 'Chelsea', 'Juventus'],
  },
  {
    id: 'wc-1958',
    sport: 'soccer',
    minLevel: 31,
    prompt: 'Which nation won the FIFA World Cup in 1958?',
    trophyIcon: T.worldCup,
    trophyLabel: 'World Cup',
    answer: 'Brazil',
    distractors: ['Sweden', 'France', 'West Germany'],
  },
  {
    id: 'euro-1992',
    sport: 'soccer',
    minLevel: 32,
    prompt: 'Which nation won UEFA Euro 1992 as last-minute replacements?',
    trophyIcon: T.euro,
    trophyLabel: 'Euro',
    answer: 'Denmark',
    distractors: ['Germany', 'Netherlands', 'Sweden'],
  },

  // ── Basketball ──
  {
    id: 'nba-2016',
    sport: 'basketball',
    minLevel: 12,
    prompt: 'Which team won the NBA Finals in 2016?',
    trophyIcon: T.nba,
    trophyLabel: 'NBA Finals',
    answer: 'Cleveland Cavaliers',
    distractors: ['Golden State Warriors', 'San Antonio Spurs', 'Oklahoma City Thunder'],
  },
  {
    id: 'nba-2011',
    sport: 'basketball',
    minLevel: 18,
    prompt: 'Which team won the NBA Finals in 2011?',
    trophyIcon: T.nba,
    trophyLabel: 'NBA Finals',
    answer: 'Dallas Mavericks',
    distractors: ['Miami Heat', 'Oklahoma City Thunder', 'Boston Celtics'],
  },
  {
    id: 'nba-2004',
    sport: 'basketball',
    minLevel: 24,
    prompt: 'Which team won the NBA Finals in 2004?',
    trophyIcon: T.nba,
    trophyLabel: 'NBA Finals',
    answer: 'Detroit Pistons',
    distractors: ['Los Angeles Lakers', 'Indiana Pacers', 'San Antonio Spurs'],
  },
  {
    id: 'nba-mvp-2017',
    sport: 'basketball',
    minLevel: 16,
    prompt: 'Who won the NBA MVP award in 2016–17?',
    trophyIcon: T.nbaMvp,
    trophyLabel: 'NBA MVP',
    answer: 'Russell Westbrook',
    distractors: ['James Harden', 'Kawhi Leonard', 'LeBron James'],
  },
  {
    id: 'nba-mvp-2011',
    sport: 'basketball',
    minLevel: 22,
    prompt: 'Who won the NBA MVP award in 2010–11?',
    trophyIcon: T.nbaMvp,
    trophyLabel: 'NBA MVP',
    answer: 'Derrick Rose',
    distractors: ['LeBron James', 'Dwight Howard', 'Kobe Bryant'],
  },
  {
    id: 'nba-dpoy-2024',
    sport: 'basketball',
    minLevel: 20,
    prompt: 'Who won NBA Defensive Player of the Year in 2023–24?',
    trophyIcon: T.generic,
    trophyLabel: 'DPOY',
    answer: 'Rudy Gobert',
    distractors: ['Bam Adebayo', 'Victor Wembanyama', 'Anthony Davis'],
  },
  {
    id: 'nba-6moy-2023',
    sport: 'basketball',
    minLevel: 27,
    prompt: 'Who won NBA Sixth Man of the Year in 2022–23?',
    trophyIcon: T.generic,
    trophyLabel: 'Sixth Man',
    answer: 'Malcolm Brogdon',
    distractors: ['Immanuel Quickley', 'Bogdan Bogdanović', 'Malik Monk'],
  },
  {
    id: 'nba-fmvp-2014',
    sport: 'basketball',
    minLevel: 29,
    prompt: 'Who was NBA Finals MVP in 2014?',
    trophyIcon: T.nba,
    trophyLabel: 'Finals MVP',
    answer: 'Kawhi Leonard',
    distractors: ['Tim Duncan', 'LeBron James', 'Tony Parker'],
  },

  // ── Baseball ──
  {
    id: 'ws-2016',
    sport: 'baseball',
    minLevel: 12,
    prompt: 'Which team won the World Series in 2016?',
    trophyIcon: T.mlb,
    trophyLabel: 'World Series',
    answer: 'Chicago Cubs',
    distractors: ['Cleveland Indians', 'Los Angeles Dodgers', 'Boston Red Sox'],
  },
  {
    id: 'ws-2004',
    sport: 'baseball',
    minLevel: 19,
    prompt: 'Which team won the World Series in 2004?',
    trophyIcon: T.mlb,
    trophyLabel: 'World Series',
    answer: 'Boston Red Sox',
    distractors: ['St. Louis Cardinals', 'New York Yankees', 'Houston Astros'],
  },
  {
    id: 'ws-1995',
    sport: 'baseball',
    minLevel: 28,
    prompt: 'Which team won the World Series in 1995?',
    trophyIcon: T.mlb,
    trophyLabel: 'World Series',
    answer: 'Atlanta Braves',
    distractors: ['Cleveland Indians', 'New York Yankees', 'Florida Marlins'],
  },
  {
    id: 'al-mvp-2017',
    sport: 'baseball',
    minLevel: 21,
    prompt: 'Who won the AL MVP award in 2017?',
    trophyIcon: T.mlbMvp,
    trophyLabel: 'AL MVP',
    answer: 'Jose Altuve',
    distractors: ['Aaron Judge', 'Mike Trout', 'José Ramírez'],
  },
  {
    id: 'cy-2018',
    sport: 'baseball',
    minLevel: 23,
    prompt: 'Who won the NL Cy Young Award in 2018?',
    trophyIcon: T.cyYoung,
    trophyLabel: 'Cy Young',
    answer: 'Jacob deGrom',
    distractors: ['Max Scherzer', 'Aaron Nola', 'Miles Mikolas'],
  },
  {
    id: 'ws-mvp-2019',
    sport: 'baseball',
    minLevel: 26,
    prompt: 'Who was World Series MVP in 2019?',
    trophyIcon: T.mlb,
    trophyLabel: 'WS MVP',
    answer: 'Stephen Strasburg',
    distractors: ['Anthony Rendon', 'Howie Kendrick', 'Juan Soto'],
  },

  // ── Football (NFL) ──
  {
    id: 'sb-lii',
    sport: 'football',
    minLevel: 14,
    prompt: 'Which team won Super Bowl LII (2018)?',
    trophyIcon: T.nfl,
    trophyLabel: 'Super Bowl',
    answer: 'Philadelphia Eagles',
    distractors: ['New England Patriots', 'Minnesota Vikings', 'Atlanta Falcons'],
  },
  {
    id: 'sb-xlii',
    sport: 'football',
    minLevel: 22,
    prompt: 'Which team won Super Bowl XLII (2008)?',
    trophyIcon: T.nfl,
    trophyLabel: 'Super Bowl',
    answer: 'New York Giants',
    distractors: ['New England Patriots', 'Green Bay Packers', 'Pittsburgh Steelers'],
  },
  {
    id: 'sb-xxxvi',
    sport: 'football',
    minLevel: 30,
    prompt: 'Which team won Super Bowl XXXVI (2002)?',
    trophyIcon: T.nfl,
    trophyLabel: 'Super Bowl',
    answer: 'New England Patriots',
    distractors: ['St. Louis Rams', 'Philadelphia Eagles', 'Pittsburgh Steelers'],
  },
  {
    id: 'nfl-mvp-2013',
    sport: 'football',
    minLevel: 25,
    prompt: 'Who won NFL MVP in 2013?',
    trophyIcon: T.generic,
    trophyLabel: 'NFL MVP',
    answer: 'Peyton Manning',
    distractors: ['Tom Brady', 'Drew Brees', 'Adrian Peterson'],
  },
  {
    id: 'sb-mvp-2014',
    sport: 'football',
    minLevel: 27,
    prompt: 'Who was Super Bowl XLVIII MVP?',
    trophyIcon: T.nfl,
    trophyLabel: 'SB MVP',
    answer: 'Malcolm Smith',
    distractors: ['Russell Wilson', 'Marshawn Lynch', 'Richard Sherman'],
  },

  // ── Hockey ──
  {
    id: 'sc-2019',
    sport: 'hockey',
    minLevel: 13,
    prompt: 'Which team won the Stanley Cup in 2019?',
    trophyIcon: T.nhl,
    trophyLabel: 'Stanley Cup',
    answer: 'St. Louis Blues',
    distractors: ['Boston Bruins', 'San Jose Sharks', 'Colorado Avalanche'],
  },
  {
    id: 'sc-2012',
    sport: 'hockey',
    minLevel: 20,
    prompt: 'Which team won the Stanley Cup in 2012?',
    trophyIcon: T.nhl,
    trophyLabel: 'Stanley Cup',
    answer: 'Los Angeles Kings',
    distractors: ['New Jersey Devils', 'Chicago Blackhawks', 'Boston Bruins'],
  },
  {
    id: 'sc-1994',
    sport: 'hockey',
    minLevel: 31,
    prompt: 'Which team won the Stanley Cup in 1994?',
    trophyIcon: T.nhl,
    trophyLabel: 'Stanley Cup',
    answer: 'New York Rangers',
    distractors: ['Vancouver Canucks', 'Montreal Canadiens', 'Detroit Red Wings'],
  },
  {
    id: 'hart-2017',
    sport: 'hockey',
    minLevel: 24,
    prompt: 'Who won the Hart Trophy (NHL MVP) in 2016–17?',
    trophyIcon: T.nhl,
    trophyLabel: 'Hart Trophy',
    answer: 'Connor McDavid',
    distractors: ['Sidney Crosby', 'Sergei Bobrovsky', 'Patrick Kane'],
  },
  {
    id: 'conn-2018',
    sport: 'hockey',
    minLevel: 28,
    prompt: 'Who won the Conn Smythe Trophy (playoff MVP) in 2018?',
    trophyIcon: T.nhl,
    trophyLabel: 'Conn Smythe',
    answer: 'Alexander Ovechkin',
    distractors: ['Braden Holtby', 'Evgeny Kuznetsov', 'Lars Eller'],
  },
  {
    id: 'calder-2020',
    sport: 'hockey',
    minLevel: 26,
    prompt: 'Who won the Calder Trophy (NHL Rookie of the Year) in 2019–20?',
    trophyIcon: T.generic,
    trophyLabel: 'Calder Trophy',
    answer: 'Cale Makar',
    distractors: ['Quinn Hughes', 'Dominik Kubalík', 'Victor Olofsson'],
  },
];
