import type { Sport } from '../types';

/** Award / curveball questions unlocked as campaign levels climb. */
export interface CampaignAwardQ {
  id: string;
  sport: Sport;
  prompt: string;
  trophyIcon: string;
  trophyLabel: string;
  answer: string;
  distractors: string[];
  /** Unlocks into the pool once campaign level ≥ this. */
  minLevel: number;
}

const T = {
  worldCup: '/icons/trophies/world-cup.png',
  euro: '/icons/trophies/euro-trophy.png',
  ucl: '/icons/trophies/ucl.png',
  ballon: '/icons/trophies/ballon-dor.png',
  nba: '/icons/trophies/nba-ring.png',
  nbaMvp: '/icons/trophies/nba-mvp.png',
  nbaScoring: '/icons/trophies/nba-scoring.png',
  mlb: '/icons/trophies/mlb-world-series.png',
  mlbMvp: '/icons/trophies/mlb-mvp.png',
  cyYoung: '/icons/trophies/mlb-cy-young.png',
  goldGlove: '/icons/trophies/mlb-gold-glove.png',
  batting: '/icons/trophies/mlb-batting-title.png',
  nfl: '/icons/trophies/nfl-super-bowl.png',
  nhl: '/icons/trophies/nhl-hof.png',
  generic: '/icons/trophy-record.png',
} as const;

export const CAMPAIGN_AWARDS: CampaignAwardQ[] = [
  // Soccer — Ballon d’Or / WC awards
  {
    id: 'bdor-2023',
    sport: 'soccer',
    minLevel: 5,
    prompt: 'Who won the Ballon d’Or in 2023?',
    trophyIcon: T.ballon,
    trophyLabel: 'Ballon d’Or',
    answer: 'Lionel Messi',
    distractors: ['Erling Haaland', 'Kylian Mbappé', 'Kevin De Bruyne'],
  },
  {
    id: 'bdor-2022',
    sport: 'soccer',
    minLevel: 6,
    prompt: 'Who won the Ballon d’Or in 2022?',
    trophyIcon: T.ballon,
    trophyLabel: 'Ballon d’Or',
    answer: 'Karim Benzema',
    distractors: ['Sadio Mané', 'Kevin De Bruyne', 'Robert Lewandowski'],
  },
  {
    id: 'bdor-2021',
    sport: 'soccer',
    minLevel: 5,
    prompt: 'Who won the Ballon d’Or in 2021?',
    trophyIcon: T.ballon,
    trophyLabel: 'Ballon d’Or',
    answer: 'Lionel Messi',
    distractors: ['Robert Lewandowski', 'Jorginho', 'Karim Benzema'],
  },
  {
    id: 'bdor-2018',
    sport: 'soccer',
    minLevel: 7,
    prompt: 'Who won the Ballon d’Or in 2018?',
    trophyIcon: T.ballon,
    trophyLabel: 'Ballon d’Or',
    answer: 'Luka Modrić',
    distractors: ['Cristiano Ronaldo', 'Mohamed Salah', 'Antoine Griezmann'],
  },
  {
    id: 'bdor-2017',
    sport: 'soccer',
    minLevel: 9,
    prompt: 'Who won the Ballon d’Or in 2017?',
    trophyIcon: T.ballon,
    trophyLabel: 'Ballon d’Or',
    answer: 'Cristiano Ronaldo',
    distractors: ['Lionel Messi', 'Neymar', 'Gianluigi Buffon'],
  },
  {
    id: 'bdor-2009',
    sport: 'soccer',
    minLevel: 10,
    prompt: 'Who won the Ballon d’Or in 2009?',
    trophyIcon: T.ballon,
    trophyLabel: 'Ballon d’Or',
    answer: 'Lionel Messi',
    distractors: ['Cristiano Ronaldo', 'Xavi', 'Andrés Iniesta'],
  },
  {
    id: 'bdor-2007',
    sport: 'soccer',
    minLevel: 22,
    prompt: 'Who won the Ballon d’Or in 2007?',
    trophyIcon: T.ballon,
    trophyLabel: 'Ballon d’Or',
    answer: 'Kaká',
    distractors: ['Cristiano Ronaldo', 'Lionel Messi', 'Ronaldinho'],
  },
  {
    id: 'bdor-f-2023',
    sport: 'soccer',
    minLevel: 18,
    prompt: 'Who won the Ballon d’Or Féminin in 2023?',
    trophyIcon: T.ballon,
    trophyLabel: 'Ballon d’Or Féminin',
    answer: 'Aitana Bonmatí',
    distractors: ['Sam Kerr', 'Alexia Putellas', 'Mary Earps'],
  },
  {
    id: 'wc-yp-2022',
    sport: 'soccer',
    minLevel: 8,
    prompt: 'Who won the Young Player award at the 2022 World Cup?',
    trophyIcon: T.worldCup,
    trophyLabel: 'Young Player',
    answer: 'Enzo Fernández',
    distractors: ['Pedri', 'Jamal Musiala', 'Jude Bellingham'],
  },
  {
    id: 'wc-yp-2018',
    sport: 'soccer',
    minLevel: 10,
    prompt: 'Who won the Young Player award at the 2018 World Cup?',
    trophyIcon: T.worldCup,
    trophyLabel: 'Young Player',
    answer: 'Kylian Mbappé',
    distractors: ['Antoine Griezmann', 'Luka Modrić', 'Harry Kane'],
  },
  {
    id: 'wc-yp-2014',
    sport: 'soccer',
    minLevel: 14,
    prompt: 'Who won the Young Player award at the 2014 World Cup?',
    trophyIcon: T.worldCup,
    trophyLabel: 'Young Player',
    answer: 'Paul Pogba',
    distractors: ['James Rodríguez', 'Neymar', 'Memphis Depay'],
  },
  {
    id: 'wc-boot-2022',
    sport: 'soccer',
    minLevel: 9,
    prompt: 'Who won the Golden Boot at the 2022 World Cup?',
    trophyIcon: T.worldCup,
    trophyLabel: 'Golden Boot',
    answer: 'Kylian Mbappé',
    distractors: ['Lionel Messi', 'Julian Álvarez', 'Olivier Giroud'],
  },
  {
    id: 'wc-ball-2022',
    sport: 'soccer',
    minLevel: 11,
    prompt: 'Who won the Golden Ball at the 2022 World Cup?',
    trophyIcon: T.worldCup,
    trophyLabel: 'Golden Ball',
    answer: 'Lionel Messi',
    distractors: ['Kylian Mbappé', 'Luka Modrić', 'Antoine Griezmann'],
  },
  {
    id: 'wc-boot-2010',
    sport: 'soccer',
    minLevel: 26,
    prompt: 'Who won the Golden Boot at the 2010 World Cup?',
    trophyIcon: T.worldCup,
    trophyLabel: 'Golden Boot',
    answer: 'Thomas Müller',
    distractors: ['David Villa', 'Wesley Sneijder', 'Diego Forlán'],
  },
  {
    id: 'pl-boot-2023',
    sport: 'soccer',
    minLevel: 7,
    prompt: 'Who won the Premier League Golden Boot in 2022–23?',
    trophyIcon: T.generic,
    trophyLabel: 'Golden Boot',
    answer: 'Erling Haaland',
    distractors: ['Harry Kane', 'Ivan Toney', 'Mohamed Salah'],
  },
  {
    id: 'pfa-2016',
    sport: 'soccer',
    minLevel: 12,
    prompt: 'Who won PFA Player of the Year in 2015–16?',
    trophyIcon: T.generic,
    trophyLabel: 'PFA POTY',
    answer: 'Riyad Mahrez',
    distractors: ['Jamie Vardy', 'Harry Kane', 'Mesut Özil'],
  },
  {
    id: 'euro-yp-2016',
    sport: 'soccer',
    minLevel: 16,
    prompt: 'Who won the Young Player award at Euro 2016?',
    trophyIcon: T.euro,
    trophyLabel: 'Young Player',
    answer: 'Renato Sanches',
    distractors: ['Kingsley Coman', 'Paul Pogba', 'Dele Alli'],
  },
  {
    id: 'ucl-boot-2014',
    sport: 'soccer',
    minLevel: 15,
    prompt: 'Who was Champions League top scorer in 2013–14?',
    trophyIcon: T.ucl,
    trophyLabel: 'UCL Top Scorer',
    answer: 'Cristiano Ronaldo',
    distractors: ['Lionel Messi', 'Zlatan Ibrahimović', 'Diego Costa'],
  },

  // Basketball
  {
    id: 'nba-mvp-2024',
    sport: 'basketball',
    minLevel: 5,
    prompt: 'Who won the NBA MVP award in 2024?',
    trophyIcon: T.nbaMvp,
    trophyLabel: 'NBA MVP',
    answer: 'Nikola Jokić',
    distractors: ['Luka Dončić', 'Shai Gilgeous-Alexander', 'Giannis Antetokounmpo'],
  },
  {
    id: 'nba-mvp-2023',
    sport: 'basketball',
    minLevel: 5,
    prompt: 'Who won the NBA MVP award in 2023?',
    trophyIcon: T.nbaMvp,
    trophyLabel: 'NBA MVP',
    answer: 'Joel Embiid',
    distractors: ['Nikola Jokić', 'Giannis Antetokounmpo', 'Jayson Tatum'],
  },
  {
    id: 'nba-mvp-2019',
    sport: 'basketball',
    minLevel: 8,
    prompt: 'Who won the NBA MVP award in 2019?',
    trophyIcon: T.nbaMvp,
    trophyLabel: 'NBA MVP',
    answer: 'Giannis Antetokounmpo',
    distractors: ['James Harden', 'Paul George', 'Nikola Jokić'],
  },
  {
    id: 'nba-mvp-2018',
    sport: 'basketball',
    minLevel: 10,
    prompt: 'Who won the NBA MVP award in 2018?',
    trophyIcon: T.nbaMvp,
    trophyLabel: 'NBA MVP',
    answer: 'James Harden',
    distractors: ['LeBron James', 'Anthony Davis', 'Giannis Antetokounmpo'],
  },
  {
    id: 'nba-mvp-2008',
    sport: 'basketball',
    minLevel: 24,
    prompt: 'Who won the NBA MVP award in 2008?',
    trophyIcon: T.nbaMvp,
    trophyLabel: 'NBA MVP',
    answer: 'Kobe Bryant',
    distractors: ['Chris Paul', 'LeBron James', 'Kevin Garnett'],
  },
  {
    id: 'nba-roy-2024',
    sport: 'basketball',
    minLevel: 8,
    prompt: 'Who won NBA Rookie of the Year in 2024?',
    trophyIcon: T.generic,
    trophyLabel: 'Rookie of the Year',
    answer: 'Victor Wembanyama',
    distractors: ['Chet Holmgren', 'Brandon Miller', 'Amen Thompson'],
  },
  {
    id: 'nba-roy-2020',
    sport: 'basketball',
    minLevel: 11,
    prompt: 'Who won NBA Rookie of the Year in 2020?',
    trophyIcon: T.generic,
    trophyLabel: 'Rookie of the Year',
    answer: 'Ja Morant',
    distractors: ['Zion Williamson', 'RJ Barrett', 'Tyler Herro'],
  },
  {
    id: 'nba-roy-2016',
    sport: 'basketball',
    minLevel: 14,
    prompt: 'Who won NBA Rookie of the Year in 2016?',
    trophyIcon: T.generic,
    trophyLabel: 'Rookie of the Year',
    answer: 'Karl-Anthony Towns',
    distractors: ['Kristaps Porziņģis', 'Jahlil Okafor', 'D’Angelo Russell'],
  },
  {
    id: 'nba-roy-2004',
    sport: 'basketball',
    minLevel: 30,
    prompt: 'Who won NBA Rookie of the Year in 2004?',
    trophyIcon: T.generic,
    trophyLabel: 'Rookie of the Year',
    answer: 'LeBron James',
    distractors: ['Carmelo Anthony', 'Dwyane Wade', 'Chris Bosh'],
  },
  {
    id: 'nba-fmvp-2023',
    sport: 'basketball',
    minLevel: 9,
    prompt: 'Who won NBA Finals MVP in 2023?',
    trophyIcon: T.nba,
    trophyLabel: 'Finals MVP',
    answer: 'Nikola Jokić',
    distractors: ['Jamal Murray', 'Jimmy Butler', 'Bam Adebayo'],
  },
  {
    id: 'nba-fmvp-2016',
    sport: 'basketball',
    minLevel: 12,
    prompt: 'Who won NBA Finals MVP in 2016?',
    trophyIcon: T.nba,
    trophyLabel: 'Finals MVP',
    answer: 'LeBron James',
    distractors: ['Kyrie Irving', 'Kevin Love', 'Stephen Curry'],
  },
  {
    id: 'nba-fmvp-2011',
    sport: 'basketball',
    minLevel: 26,
    prompt: 'Who won NBA Finals MVP in 2011?',
    trophyIcon: T.nba,
    trophyLabel: 'Finals MVP',
    answer: 'Dirk Nowitzki',
    distractors: ['LeBron James', 'Dwyane Wade', 'Jason Terry'],
  },
  {
    id: 'nba-dpoy-2023',
    sport: 'basketball',
    minLevel: 16,
    prompt: 'Who won NBA Defensive Player of the Year in 2023?',
    trophyIcon: T.generic,
    trophyLabel: 'DPOY',
    answer: 'Jaren Jackson Jr.',
    distractors: ['Brook Lopez', 'Evan Mobley', 'Bam Adebayo'],
  },
  {
    id: 'nba-scoring-2024',
    sport: 'basketball',
    minLevel: 15,
    prompt: 'Who led the NBA in scoring in 2023–24?',
    trophyIcon: T.nbaScoring,
    trophyLabel: 'Scoring Title',
    answer: 'Luka Dončić',
    distractors: ['Giannis Antetokounmpo', 'Shai Gilgeous-Alexander', 'Kevin Durant'],
  },
  {
    id: 'nba-6moy-2023',
    sport: 'basketball',
    minLevel: 20,
    prompt: 'Who won NBA Sixth Man of the Year in 2023?',
    trophyIcon: T.generic,
    trophyLabel: 'Sixth Man',
    answer: 'Malcolm Brogdon',
    distractors: ['Immanuel Quickley', 'Bobby Portis', 'Norman Powell'],
  },

  // Baseball
  {
    id: 'mlb-mvp-al-2024',
    sport: 'baseball',
    minLevel: 5,
    prompt: 'Who won the AL MVP award in 2024?',
    trophyIcon: T.mlbMvp,
    trophyLabel: 'AL MVP',
    answer: 'Aaron Judge',
    distractors: ['Juan Soto', 'Bobby Witt Jr.', 'Gunnar Henderson'],
  },
  {
    id: 'mlb-mvp-al-2023',
    sport: 'baseball',
    minLevel: 5,
    prompt: 'Who won the AL MVP award in 2023?',
    trophyIcon: T.mlbMvp,
    trophyLabel: 'AL MVP',
    answer: 'Shohei Ohtani',
    distractors: ['Corey Seager', 'Aaron Judge', 'Yordan Alvarez'],
  },
  {
    id: 'mlb-mvp-nl-2023',
    sport: 'baseball',
    minLevel: 6,
    prompt: 'Who won the NL MVP award in 2023?',
    trophyIcon: T.mlbMvp,
    trophyLabel: 'NL MVP',
    answer: 'Ronald Acuña Jr.',
    distractors: ['Mookie Betts', 'Freddie Freeman', 'Matt Olson'],
  },
  {
    id: 'mlb-mvp-nl-2018',
    sport: 'baseball',
    minLevel: 22,
    prompt: 'Who won NL MVP in 2018?',
    trophyIcon: T.mlbMvp,
    trophyLabel: 'NL MVP',
    answer: 'Christian Yelich',
    distractors: ['Javier Báez', 'Nolan Arenado', 'Paul Goldschmidt'],
  },
  {
    id: 'cy-al-2022',
    sport: 'baseball',
    minLevel: 9,
    prompt: 'Who won the AL Cy Young Award in 2022?',
    trophyIcon: T.cyYoung,
    trophyLabel: 'Cy Young',
    answer: 'Justin Verlander',
    distractors: ['Dylan Cease', 'Alek Manoah', 'Shohei Ohtani'],
  },
  {
    id: 'cy-nl-2023',
    sport: 'baseball',
    minLevel: 10,
    prompt: 'Who won the NL Cy Young Award in 2023?',
    trophyIcon: T.cyYoung,
    trophyLabel: 'Cy Young',
    answer: 'Blake Snell',
    distractors: ['Zac Gallen', 'Spencer Strider', 'Justin Steele'],
  },
  {
    id: 'cy-al-2014',
    sport: 'baseball',
    minLevel: 32,
    prompt: 'Who won the AL Cy Young Award in 2014?',
    trophyIcon: T.cyYoung,
    trophyLabel: 'Cy Young',
    answer: 'Corey Kluber',
    distractors: ['Felix Hernández', 'Chris Sale', 'Max Scherzer'],
  },
  {
    id: 'mlb-roy-al-2023',
    sport: 'baseball',
    minLevel: 8,
    prompt: 'Who won AL Rookie of the Year in 2023?',
    trophyIcon: T.generic,
    trophyLabel: 'Rookie of the Year',
    answer: 'Gunnar Henderson',
    distractors: ['Triston Casas', 'Josh Jung', 'Masataka Yoshida'],
  },
  {
    id: 'mlb-roy-nl-2021',
    sport: 'baseball',
    minLevel: 13,
    prompt: 'Who won NL Rookie of the Year in 2021?',
    trophyIcon: T.generic,
    trophyLabel: 'Rookie of the Year',
    answer: 'Jonathan India',
    distractors: ['Trevor Rogers', 'Dylan Carlson', 'Patrick Wisdom'],
  },
  {
    id: 'ws-mvp-2016',
    sport: 'baseball',
    minLevel: 15,
    prompt: 'Who won World Series MVP in 2016?',
    trophyIcon: T.mlb,
    trophyLabel: 'WS MVP',
    answer: 'Ben Zobrist',
    distractors: ['Kris Bryant', 'Jon Lester', 'Anthony Rizzo'],
  },
  {
    id: 'mlb-bat-2023',
    sport: 'baseball',
    minLevel: 17,
    prompt: 'Who won the NL batting title in 2023?',
    trophyIcon: T.batting,
    trophyLabel: 'Batting Title',
    answer: 'Luis Arraez',
    distractors: ['Ronald Acuña Jr.', 'Freddie Freeman', 'Mookie Betts'],
  },
  {
    id: 'gg-ozzie',
    sport: 'baseball',
    minLevel: 23,
    prompt: 'Which shortstop is famous for a record streak of Gold Gloves?',
    trophyIcon: T.goldGlove,
    trophyLabel: 'Gold Glove',
    answer: 'Ozzie Smith',
    distractors: ['Derek Jeter', 'Cal Ripken Jr.', 'Alex Rodriguez'],
  },

  // Football / NFL
  {
    id: 'nfl-mvp-2024',
    sport: 'football',
    minLevel: 5,
    prompt: 'Who won NFL MVP for the 2024 season?',
    trophyIcon: T.generic,
    trophyLabel: 'NFL MVP',
    answer: 'Josh Allen',
    distractors: ['Lamar Jackson', 'Saquon Barkley', 'Joe Burrow'],
  },
  {
    id: 'nfl-mvp-2023',
    sport: 'football',
    minLevel: 5,
    prompt: 'Who won NFL MVP for the 2023 season?',
    trophyIcon: T.generic,
    trophyLabel: 'NFL MVP',
    answer: 'Lamar Jackson',
    distractors: ['Josh Allen', 'Dak Prescott', 'Christian McCaffrey'],
  },
  {
    id: 'nfl-mvp-2019',
    sport: 'football',
    minLevel: 9,
    prompt: 'Who won NFL MVP for the 2019 season?',
    trophyIcon: T.generic,
    trophyLabel: 'NFL MVP',
    answer: 'Lamar Jackson',
    distractors: ['Russell Wilson', 'Patrick Mahomes', 'Derrick Henry'],
  },
  {
    id: 'nfl-mvp-2007',
    sport: 'football',
    minLevel: 25,
    prompt: 'Who won NFL MVP for the 2007 season?',
    trophyIcon: T.generic,
    trophyLabel: 'NFL MVP',
    answer: 'Tom Brady',
    distractors: ['Brett Favre', 'Peyton Manning', 'LaDainian Tomlinson'],
  },
  {
    id: 'nfl-oroy-2023',
    sport: 'football',
    minLevel: 8,
    prompt: 'Who won Offensive Rookie of the Year for 2023?',
    trophyIcon: T.generic,
    trophyLabel: 'OROY',
    answer: 'C.J. Stroud',
    distractors: ['Anthony Richardson', 'Puka Nacua', 'Bijan Robinson'],
  },
  {
    id: 'nfl-droy-2023',
    sport: 'football',
    minLevel: 10,
    prompt: 'Who won Defensive Rookie of the Year for 2023?',
    trophyIcon: T.generic,
    trophyLabel: 'DROY',
    answer: 'Will Anderson Jr.',
    distractors: ['Jalen Carter', 'Devon Witherspoon', 'Christian Gonzalez'],
  },
  {
    id: 'nfl-opoy-2023',
    sport: 'football',
    minLevel: 12,
    prompt: 'Who won Offensive Player of the Year for 2023?',
    trophyIcon: T.generic,
    trophyLabel: 'OPOY',
    answer: 'Christian McCaffrey',
    distractors: ['Tyreek Hill', 'CeeDee Lamb', 'Josh Allen'],
  },
  {
    id: 'nfl-dpoy-2023',
    sport: 'football',
    minLevel: 15,
    prompt: 'Who won Defensive Player of the Year for 2023?',
    trophyIcon: T.generic,
    trophyLabel: 'DPOY',
    answer: 'Myles Garrett',
    distractors: ['T.J. Watt', 'Micah Parsons', 'Maxx Crosby'],
  },
  {
    id: 'sb-mvp-2025',
    sport: 'football',
    minLevel: 7,
    prompt: 'Who won Super Bowl LIX MVP?',
    trophyIcon: T.nfl,
    trophyLabel: 'SB MVP',
    answer: 'Jalen Hurts',
    distractors: ['Patrick Mahomes', 'Saquon Barkley', 'A.J. Brown'],
  },
  {
    id: 'sb-mvp-2024',
    sport: 'football',
    minLevel: 8,
    prompt: 'Who won Super Bowl LVIII MVP?',
    trophyIcon: T.nfl,
    trophyLabel: 'SB MVP',
    answer: 'Patrick Mahomes',
    distractors: ['Travis Kelce', 'Christian McCaffrey', 'Brock Purdy'],
  },
  {
    id: 'sb-mvp-2015',
    sport: 'football',
    minLevel: 18,
    prompt: 'Who won Super Bowl XLIX MVP?',
    trophyIcon: T.nfl,
    trophyLabel: 'SB MVP',
    answer: 'Tom Brady',
    distractors: ['Malcolm Butler', 'Marshawn Lynch', 'Russell Wilson'],
  },
  {
    id: 'sb-mvp-2008',
    sport: 'football',
    minLevel: 28,
    prompt: 'Who won Super Bowl XLII MVP?',
    trophyIcon: T.nfl,
    trophyLabel: 'SB MVP',
    answer: 'Eli Manning',
    distractors: ['David Tyree', 'Plaxico Burress', 'Tom Brady'],
  },

  // Hockey
  {
    id: 'nhl-hart-2024',
    sport: 'hockey',
    minLevel: 5,
    prompt: 'Who won the Hart Trophy (NHL MVP) in 2024?',
    trophyIcon: T.nhl,
    trophyLabel: 'Hart Trophy',
    answer: 'Nathan MacKinnon',
    distractors: ['Connor McDavid', 'Nikita Kucherov', 'Auston Matthews'],
  },
  {
    id: 'nhl-hart-2023',
    sport: 'hockey',
    minLevel: 5,
    prompt: 'Who won the Hart Trophy (NHL MVP) in 2023?',
    trophyIcon: T.nhl,
    trophyLabel: 'Hart Trophy',
    answer: 'Connor McDavid',
    distractors: ['David Pastrňák', 'Matthew Tkachuk', 'Leon Draisaitl'],
  },
  {
    id: 'nhl-hart-2021',
    sport: 'hockey',
    minLevel: 9,
    prompt: 'Who won the Hart Trophy in 2021?',
    trophyIcon: T.nhl,
    trophyLabel: 'Hart Trophy',
    answer: 'Connor McDavid',
    distractors: ['Auston Matthews', 'Nathan MacKinnon', 'Brad Marchand'],
  },
  {
    id: 'nhl-hart-1997',
    sport: 'hockey',
    minLevel: 28,
    prompt: 'Who won the Hart Trophy in 1997?',
    trophyIcon: T.nhl,
    trophyLabel: 'Hart Trophy',
    answer: 'Dominik Hašek',
    distractors: ['Mario Lemieux', 'Wayne Gretzky', 'Paul Kariya'],
  },
  {
    id: 'nhl-calder-2024',
    sport: 'hockey',
    minLevel: 8,
    prompt: 'Who won the Calder Trophy (Rookie of the Year) in 2024?',
    trophyIcon: T.generic,
    trophyLabel: 'Calder Trophy',
    answer: 'Connor Bedard',
    distractors: ['Luke Hughes', 'Adam Fantilli', 'Logan Cooley'],
  },
  {
    id: 'nhl-calder-2023',
    sport: 'hockey',
    minLevel: 10,
    prompt: 'Who won the Calder Trophy in 2023?',
    trophyIcon: T.generic,
    trophyLabel: 'Calder Trophy',
    answer: 'Matty Beniers',
    distractors: ['Owen Power', 'Wyatt Johnston', 'Matias Maccelli'],
  },
  {
    id: 'nhl-calder-2016',
    sport: 'hockey',
    minLevel: 30,
    prompt: 'Who won the Calder Trophy in 2016?',
    trophyIcon: T.generic,
    trophyLabel: 'Calder Trophy',
    answer: 'Artemi Panarin',
    distractors: ['Connor McDavid', 'Shayne Gostisbehere', 'Jack Eichel'],
  },
  {
    id: 'nhl-vezina-2023',
    sport: 'hockey',
    minLevel: 13,
    prompt: 'Who won the Vezina Trophy (best goalie) in 2023?',
    trophyIcon: T.nhl,
    trophyLabel: 'Vezina Trophy',
    answer: 'Linus Ullmark',
    distractors: ['Ilya Sorokin', 'Connor Hellebuyck', 'Jake Oettinger'],
  },
  {
    id: 'nhl-norris-2024',
    sport: 'hockey',
    minLevel: 14,
    prompt: 'Who won the Norris Trophy (best defenseman) in 2024?',
    trophyIcon: T.nhl,
    trophyLabel: 'Norris Trophy',
    answer: 'Quinn Hughes',
    distractors: ['Cale Makar', 'Roman Josi', 'Adam Fox'],
  },
  {
    id: 'nhl-smythe-2024',
    sport: 'hockey',
    minLevel: 11,
    prompt: 'Who won the Conn Smythe Trophy (playoff MVP) in 2024?',
    trophyIcon: T.nhl,
    trophyLabel: 'Conn Smythe',
    answer: 'Connor McDavid',
    distractors: ['Aleksander Barkov', 'Sergei Bobrovsky', 'Matthew Tkachuk'],
  },
  {
    id: 'nhl-rocket-2022',
    sport: 'hockey',
    minLevel: 17,
    prompt: 'Who won the Rocket Richard Trophy (most goals) in 2022?',
    trophyIcon: T.generic,
    trophyLabel: 'Rocket Richard',
    answer: 'Auston Matthews',
    distractors: ['Leon Draisaitl', 'Chris Kreider', 'Alex Ovechkin'],
  },
  {
    id: 'nhl-ross-2023',
    sport: 'hockey',
    minLevel: 19,
    prompt: 'Who won the Art Ross Trophy (most points) in 2023?',
    trophyIcon: T.nhl,
    trophyLabel: 'Art Ross',
    answer: 'Connor McDavid',
    distractors: ['Leon Draisaitl', 'Nikita Kucherov', 'David Pastrňák'],
  },
];
